export const getBoard = () => {
  return {
    name: "Propostas",
    columns: [
      {
        id: 12232,
        title: "Leads Qualificados",
        cards: [
          {
            id: 1,
            company: "New Company",
            user: "Pedro Paulo",
            views: 2,
            proposals: 9,
            proposalMin: "R$ 10.000,00",
            proposalMax: "R$ 20.550,00",
            daysLeft: 13,
            hasTransaction: true,
            ticket: "#23010504",
            labels: ["briefcase", "money", "report"],
            canDrag: true,
          },
          {
            id: 205,
            company: "Prospect Company",
            user: "Pedro Paulo",
            views: 0,
            proposals: 1,
            proposalMin: "R$ 12.780,00",
            proposalMax: "",
            daysLeft: 0,
            hasTransaction: true,
            ticket: "#23518902",
            labels: ["briefcase", "money"],
            canDrag: true,
          },
          {
            id: 3,
            company: "Try now",
            user: "Salesman one",
            views: 4,
            proposals: 1,
            proposalMin: "R$ 12.000,00",
            proposalMax: "R$ 31.801,00",
            daysLeft: 84,
            hasTransaction: true,
            ticket: "#23993844",
            labels: ["report"],
            canDrag: true,
          },
          {
            id: 89,
            company: "Let's Rock Company",
            user: "Mr.",
            views: 1,
            proposals: 0,
            proposalMin: "R$ 123.800,00",
            proposalMax: "R$ 200.125,00",
            daysLeft: 22,
            hasTransaction: true,
            ticket: "#23993844",
            labels: ["report"],
            canDrag: true,
          },
          {
            id: 52,
            company: "Bee-Have",
            user: "Api Cultor",
            views: 1,
            proposals: 0,
            proposalMin: "R$ 200,00",
            proposalMax: "R$ 221,00",
            daysLeft: 40,
            hasTransaction: true,
            ticket: "#15148886",
            labels: ["report"],
            canDrag: true,
          },
          {
            id: 9999999,
            company: "",
            user: "",
            views: 0,
            proposals: 0,
            proposalMin: "",
            proposalMax: "",
            daysLeft: 0,
            hasTransaction: true,
            ticket: "",
            labels: [],
            canDrag: false,
          },
        ],
      },
      {
        id: 2888,
        title: "Reunião Encantamentos",
        cards: [
          {
            id: 432,
            company: "IWC",
            user: "Pedro Paulo",
            views: 2,
            proposals: 3,
            proposalMin: "R$ 10.000,00",
            proposalMax: "R$ 20.550,00",
            daysLeft: 13,
            hasTransaction: true,
            ticket: "#23010504",
            labels: ["briefcase", "money", "report"],
            canDrag: true,
          },
          {
            id: 78686,
            company: "CTMEDH",
            user: "Silvia Almeida",
            views: 4,
            proposals: 1,
            proposalMin: "R$ 73.000,00",
            proposalMax: "R$ 85.801,00",
            daysLeft: 28,
            hasTransaction: true,
            ticket: "#23915940",
            labels: ["report"],
            canDrag: true,
          },
          {
            id: 9999999,
            company: "",
            user: "",
            views: 0,
            proposals: 0,
            proposalMin: "",
            proposalMax: "",
            daysLeft: 0,
            hasTransaction: true,
            ticket: "",
            labels: [],
            canDrag: false,
          },
        ],
      },
      {
        id: 983,
        title: "Propostas Enviadas",
        cards: [
          {
            id: 77,
            company: "IWC",
            user: "Pedro Paulo",
            views: 2,
            proposals: 3,
            proposalMin: "R$ 10.000,00",
            proposalMax: "R$ 20.550,00",
            daysLeft: 13,
            hasTransaction: true,
            ticket: "#23010504",
            labels: ["briefcase", "money", "report"],
            canDrag: true,
          },
          {
            id: 88,
            company: "DORT",
            user: "John Brave",
            views: 0,
            proposals: 1,
            proposalMin: "R$ 1.780,00",
            proposalMax: "R$ 2.920,00",
            daysLeft: 4,
            hasTransaction: true,
            ticket: "#23518902",
            labels: ["briefcase", "money"],
            canDrag: true,
          },
          {
            id: 99,
            company: "CTMEDH",
            user: "Silvia Almeida",
            views: 4,
            proposals: 1,
            proposalMin: "R$ 73.000,00",
            proposalMax: "R$ 85.801,00",
            daysLeft: 28,
            hasTransaction: true,
            ticket: "#12347888",
            labels: ["report"],
            canDrag: true,
          },
          {
            id: 99,
            company: "TTDDD",
            user: "Tech team",
            views: 8,
            proposals: 8,
            proposalMin: "R$ 130.000,00",
            proposalMax: "R$ 150.000,00",
            daysLeft: 10,
            hasTransaction: true,
            ticket: "#2255888",
            labels: ["report"],
            canDrag: true,
          },
          {
            id: 9999999,
            company: "",
            user: "",
            views: 0,
            proposals: 0,
            proposalMin: "",
            proposalMax: "",
            daysLeft: 0,
            hasTransaction: true,
            ticket: "",
            labels: [],
            canDrag: false,
          },
        ],
      },
    ],
  };
};
