export const getBoard = () => {
  return {
    board: "Propostas",
    columns: [
      {
        id: Math.random(),
        title: "Leads Qualificados",
        cards: [
          {
            id: Math.random(),
            company: "IWC",
            user: "Pedro Paulo",
            views: 2,
            proposals: 3,
            proposalMin: "R$ 10.000,00",
            proposalMax: "R$ 20.550,00",
            daysLeft: 13,
            hasTransaction: true,
            ticket: "#23010504",
            labels: ["briefcase", "money", "report"],
            editable: true,
          },
          {
            id: Math.random(),
            company: "DORT",
            user: "John Brave",
            views: 0,
            proposals: 1,
            proposalMin: "R$ 1.780,00",
            proposalMax: "R$ 2.920,00",
            daysLeft: 4,
            hasTransaction: true,
            ticket: "#23518902",
            labels: ["briefcase", "money"],
            editable: true,
          },
          {
            id: Math.random(),
            company: "CTMEDH",
            user: "Silvia Almeida",
            views: 4,
            proposals: 1,
            proposalMin: "R$ 73.000,00",
            proposalMax: "R$ 85.801,00",
            daysLeft: 28,
            hasTransaction: true,
            ticket: "#23993844",
            labels: ["report"],
            editable: true,
          },
        ],
      },
      {
        id: Math.random(),
        title: "Reunião Encantamentos",
        cards: [
          {
            id: Math.random(),
            company: "IWC",
            user: "Pedro Paulo",
            views: 2,
            proposals: 3,
            proposalMin: "R$ 10.000,00",
            proposalMax: "R$ 20.550,00",
            daysLeft: 13,
            hasTransaction: true,
            ticket: "#23010504",
            labels: ["briefcase", "money", "report"],
            editable: true,
          },
          {
            id: Math.random(),
            company: "DORT",
            user: "John Brave",
            views: 0,
            proposals: 1,
            proposalMin: "R$ 1.780,00",
            proposalMax: "R$ 2.920,00",
            daysLeft: 4,
            hasTransaction: true,
            ticket: "#23518902",
            labels: ["briefcase", "money"],
            editable: true,
          },
          {
            id: Math.random(),
            company: "CTMEDH",
            user: "Silvia Almeida",
            views: 4,
            proposals: 1,
            proposalMin: "R$ 73.000,00",
            proposalMax: "R$ 85.801,00",
            daysLeft: 28,
            hasTransaction: true,
            ticket: "#23993844",
            labels: ["report"],
            editable: true,
          },
        ],
      },
      {
        id: Math.random(),
        title: "Propostas Enviadas",
        cards: [
          {
            id: Math.random(),
            company: "IWC",
            user: "Pedro Paulo",
            views: 2,
            proposals: 3,
            proposalMin: "R$ 10.000,00",
            proposalMax: "R$ 20.550,00",
            daysLeft: 13,
            hasTransaction: true,
            ticket: "#23010504",
            labels: ["briefcase", "money", "report"],
            editable: true,
          },
          {
            id: Math.random(),
            company: "DORT",
            user: "John Brave",
            views: 0,
            proposals: 1,
            proposalMin: "R$ 1.780,00",
            proposalMax: "R$ 2.920,00",
            daysLeft: 4,
            hasTransaction: true,
            ticket: "#23518902",
            labels: ["briefcase", "money"],
            editable: true,
          },
          {
            id: Math.random(),
            company: "CTMEDH",
            user: "Silvia Almeida",
            views: 4,
            proposals: 1,
            proposalMin: "R$ 73.000,00",
            proposalMax: "R$ 85.801,00",
            daysLeft: 28,
            hasTransaction: true,
            ticket: "#23993844",
            labels: ["report"],
            editable: true,
          },
        ],
      },
    ],
  };
};
